name: Auto Commit

on:
    schedule:
        # Programa para executar em horários específicos (neste exemplo, diariamente às 20:00 UTC)
        - cron: "0 20 * * *"

    # Permite rodar manualmente a partir da interface do GitHub
    workflow_dispatch:

jobs:
    auto-commit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Git
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            - name: Check for changes
              id: check_changes
              run: |
                  # Aqui você poderia adicionar comandos para gerar/atualizar dados
                  # Por exemplo, scripts Python que atualizam arquivos

                  # Verifica se há alterações para commitar
                  git add .
                  if git diff --staged --quiet; then
                    echo "::set-output name=changes_exist::false"
                  else
                    echo "::set-output name=changes_exist::true"
                  fi

            - name: Commit and push if changes exist
              if: steps.check_changes.outputs.changes_exist == 'true'
              run: |
                  git commit -m "Auto commit: Atualizações automáticas em $(date +'%Y-%m-%d %H:%M:%S')"
                  git push
